name: Release

on:
  release: 
    types: [prereleased, published]
  schedule:
    - cron: '0 0 * * 1' 

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_USER_RECEIVER: ${{ secrets.EMAIL_USER_RECEIVER }}
        run: go test -v ./...

      - name: Release
        id: release
        run: |
          echo "Creating a release..."
          GOPROXY=proxy.golang.org go list -m github.com/patrickkabwe/gomailer@${{ github.event.release.tag_name }}
          echo "Release created!"

              